# Previsão de aprovação de empréstimo
Objetivo: Prever se o cliente pode ser aprovado ou não para pegar empréstimo

[https://www.kaggle.com/datasets/architsharma01/loan-approval-prediction-dataset](https://www.kaggle.com/datasets/architsharma01/loan-approval-prediction-dataset)

In [1]:
# importar o pandas
import pandas as pd
import numpy as np

In [2]:
# importar os dados
tabela = pd.read_csv('analise_emprestimo.csv')
tabela.head(3)

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected

In [3]:
!pip install ydata-profiling

In [4]:
from ydata_profiling import ProfileReport

In [48]:
profile = ProfileReport(tabela, title="Aprovação de Emprestimo")

In [49]:
profile.to_file("aprovacao.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
# informação da tabela
tabela.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   loan_id                    4269 non-null   int64 
 1    no_of_dependents          4269 non-null   int64 
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64 
 5    loan_amount               4269 non-null   int64 
 6    loan_term                 4269 non-null   int64 
 7    cibil_score               4269 non-null   int64 
 8    residential_assets_value  4269 non-null   int64 
 9    commercial_assets_value   4269 non-null   int64 
 10   luxury_assets_value       4269 non-null   int64 
 11   bank_asset_value          4269 non-null   int64 
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB


In [6]:
tabela.describe()

loan_id   no_of_dependents   income_annum   loan_amount  \
count  4269.000000        4269.000000   4.269000e+03  4.269000e+03   
mean   2135.000000           2.498712   5.059124e+06  1.513345e+07   
std    1232.498479           1.695910   2.806840e+06  9.043363e+06   
min       1.000000           0.000000   2.000000e+05  3.000000e+05   
25%    1068.000000           1.000000   2.700000e+06  7.700000e+06   
50%    2135.000000           3.000000   5.100000e+06  1.450000e+07   
75%    3202.000000           4.000000   7.500000e+06  2.150000e+07   
max    4269.000000           5.000000   9.900000e+06  3.950000e+07   

         loan_term   cibil_score   residential_assets_value  \
count  4269.000000   4269.000000               4.269000e+03   
mean     10.900445    599.936051               7.472617e+06   
std       5.709187    172.430401               6.503637e+06   
min       2.000000    300.000000              -1.000000e+05   
25%       6.000000    453.000000               2.200000e+06   
50%      10.000000    600.000000               5.600000e+06   
75%      16.000000    748.000000               1.130000e+07   
max      20.000000    900.000000               2.910000e+07   

        commercial_assets_value   luxury_assets_value   bank_asset_value  
count              4.269000e+03          4.269000e+03       4.269000e+03  
mean               4.973155e+06          1.512631e+07       4.976692e+06  
std                4.388966e+06          9.103754e+06       3.250185e+06  
min                0.000000e+00          3.000000e+05       0.000000e+00  
25%                1.300000e+06          7.500000e+06       2.300000e+06  
50%                3.700000e+06          1.460000e+07       4.600000e+06  
75%                7.600000e+06          2.170000e+07       7.100000e+06  
max                1.940000e+07          3.920000e+07       1.470000e+07

In [7]:
# analisar valores nulos
tabela.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [8]:
tabela.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [9]:
tabela.columns = ['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status']

## Verificando valores únicos

In [10]:
tabela.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [11]:
tabela.self_employed.unique()

array([' No', ' Yes'], dtype=object)

In [12]:
tabela.loan_status.unique()

array([' Approved', ' Rejected'], dtype=object)

In [13]:
tabela.education = tabela.education.apply(lambda x: 0 if x == ' Graduate' else 1)

In [14]:
tabela.self_employed = tabela.self_employed.apply(lambda x: 0 if x == ' No' else 1)

In [15]:
tabela.loan_status = tabela.loan_status.apply(lambda x: 0 if x == ' Approved' else 1)

## Legenda
* educação
    * 0 - Graduate
    * 1 - Not Graduate
* trabalho
    * 0 - Não
    * 1 - Sim
* aprovação
    * 0 - aprovado
    * 1 - reprovado

In [16]:
tabela.head(3)

loan_id  no_of_dependents  education  self_employed  income_annum  \
0        1                 2          0              0       9600000   
1        2                 0          1              1       4100000   
2        3                 3          0              0       9100000   

   loan_amount  loan_term  cibil_score  residential_assets_value  \
0     29900000         12          778                   2400000   
1     12200000          8          417                   2700000   
2     29700000         20          506                   7100000   

   commercial_assets_value  luxury_assets_value  bank_asset_value  loan_status  
0                 17600000             22700000           8000000            0  
1                  2200000              8800000           3300000            1  
2                  4500000             33300000          12800000            1

In [17]:
tabela.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   int64
 3   self_employed             4269 non-null   int64
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   int64
dtypes: int64(13)
memory usage: 433.7 KB


In [18]:
tabela2 = tabela.drop('loan_id', axis=1)

In [19]:
tabela2.head(3)

no_of_dependents  education  self_employed  income_annum  loan_amount  \
0                 2          0              0       9600000     29900000   
1                 0          1              1       4100000     12200000   
2                 3          0              0       9100000     29700000   

   loan_term  cibil_score  residential_assets_value  commercial_assets_value  \
0         12          778                   2400000                 17600000   
1          8          417                   2700000                  2200000   
2         20          506                   7100000                  4500000   

   luxury_assets_value  bank_asset_value  loan_status  
0             22700000           8000000            0  
1              8800000           3300000            1  
2             33300000          12800000            1

In [20]:
# separar os previsores e alvo
X = tabela2.drop('loan_status', axis=1)
y = tabela2['loan_status']

In [21]:
# importação
from sklearn.model_selection import train_test_split

In [22]:
# separar a base de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

## KNN

In [23]:
# knn
from sklearn.neighbors import KNeighborsClassifier

In [24]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [25]:
previsoes_knn = knn.predict(X_test)
previsoes_knn

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
accuracy_score(y_test, previsoes_knn)

0.6104605776736924

In [28]:
confusion_matrix(y_test, previsoes_knn)

array([[699, 111],
       [388,  83]], dtype=int64)

In [29]:
previsoes_treino = knn.predict(X_train)
previsoes_treino

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [30]:
accuracy_score(y_train, previsoes_treino)

0.6864123159303882

In [31]:
confusion_matrix(y_train, previsoes_treino)

array([[1709,  137],
       [ 800,  342]], dtype=int64)

## Árvore de Decisão

In [32]:
from sklearn import tree

In [33]:
clf_ar = tree.DecisionTreeClassifier(max_depth=6)
clf_ar = clf_ar.fit(X_train, y_train)

In [34]:
previsoes_clf_ar = clf_ar.predict(X_test)
previsoes_clf_ar

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [35]:
accuracy_score(y_test, previsoes_clf_ar)

0.9687743950039032

In [36]:
confusion_matrix(y_test, previsoes_clf_ar)

array([[805,   5],
       [ 35, 436]], dtype=int64)

In [37]:
previsoes_treino = clf_ar.predict(X_train)
previsoes_treino

array([1, 0, 0, ..., 1, 1, 0], dtype=int64)

In [38]:
accuracy_score(y_train, previsoes_treino)

0.9792503346720214

In [39]:
confusion_matrix(y_train, previsoes_treino)

array([[1845,    1],
       [  61, 1081]], dtype=int64)

## Random Forest

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
clf_rf = RandomForestClassifier(n_estimators=10)
clf_rf = clf_rf.fit(X_train, y_train)

In [42]:
previsoes_clf_rf = clf_rf.predict(X_test)
previsoes_clf_rf

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [43]:
accuracy_score(y_test, previsoes_clf_rf)

0.970335675253708

In [44]:
confusion_matrix(y_test, previsoes_clf_rf)

array([[795,  15],
       [ 23, 448]], dtype=int64)

In [45]:
previsoes_treino = clf_rf.predict(X_train)
previsoes_treino

array([1, 0, 0, ..., 1, 1, 0], dtype=int64)

In [46]:
accuracy_score(y_train, previsoes_treino)

0.9983266398929049

In [47]:
confusion_matrix(y_train, previsoes_treino)

array([[1845,    1],
       [   4, 1138]], dtype=int64)